### PR TITLE
[DNM]: stm32 device only usb driver support

### PR DESCRIPTION
**Pull request by qianfan-Zhao**
Hi:
first times i did not see the code in function **usb_dc_ep_configure** which config pma address. so i and this commit and try pull request.

But you should try this pull request, now stm32f1's usb can work. I think we need config pma address before HAL_PCD_Start, like cubemx did. 

By the way, zephyr doesn't create new hex file if that file already exist. that make me using the lastest source code, but always downloading previous version.

### CODE REVIEW

**Comment by zhaozhongchen** [comment]
sorry, the origin source code is configured pma address, not this reason

**Comment by ydamigos** [comment]
Hi,

I think I have tried this and didn't work. Maybe something else was broken at that moment. I will try it again.

**Comment by qianfan-Zhao** [comment]
I have test this code on stm32f103 and linux, every thing is ok.

```
 usb 2-2: new full-speed USB device number 86 using at91_ohci
[19127.640625] usb 2-2: New USB device found, idVendor=dead, idProduct=beef
[19127.648437] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[19127.656250] usb 2-2: Product: USB-DEV
[19127.656250] usb 2-2: Manufacturer: ZEPHYR
[19127.664062] usb 2-2: SerialNumber: 0.01
[19127.671875] cdc_acm 2-2:1.0: ttyACM0: USB ACM device

# microcom -s 115200 /dev/ttyACM0
Send characters to the UART device
Characters read:
AT

```

**Comment by ydamigos** [comment]
It is great that it is working, but I need to test it also on my f1 board and boards from other families and prepare a PR for zephyr.
I will need also a "Signed-off-by:" line in your commits because this PR will be squashed in mine and I will add you there.
Moreover, the usb support for all stm32 families is based on dts support for stm32 usb and will be postponed until my PR (under review by zephyr community) which enables dts support for stm32 usb is merged.

**Comment by qianfan-Zhao** [comment]
I will do more test on my stm32f1 board and make sure there isn't has other problems.

**Comment by ydamigos** [comment]
I just test this patch on my board and it didn't work.

**Comment by qianfan-Zhao** [comment]
which board are you using？ have you capture some usb packets, bus hound is a good tools. wireshark also can do that.

what's you changed after this pr? now branch was conflicts

**Comment by ydamigos** [comment]
My board fails to reply to host's configuration request.

I am using [olimexino_stm32 board](https://www.olimex.com/Products/Duino/STM32/OLIMEXINO-STM32/open-source-hardware). I am using wireshark to capture the packets, I don't have a hardware usb analyzer.

I added  HAL_PCDEx_SetConnectionState function to handle the usb disconnect pin in "HAL way". Now HAL_PCD_Start calls HAL_PCDEx_SetConnectionState to enable the pull-up resistor on USB-DP.
You don't need 2a8f363de5687e427274ab520b7c30e12609c491,  HAL_PCDEx_SetConnectionState should enable pull-up resistor.

**Comment by ydamigos** [comment]
The stm32-usb-v2 branch partially works with my board if I set SYS_LOGs to zero. If I don't it throws timeout errors. The board is recognized as an ACM device but it fails sometimes when I try to connect to it.

**Comment by qianfan-Zhao** [comment]
I know that's why sometimes usb host doesn't recognized because i found that by usb monitor. I will email you the log when Monday, and fix this bug.

My board doesn't have a gpio pin to enable usb pull up resistor, may be that's why my board work fine but yours not.

I don't know where 2a8f363 come from, i rebase to yours branch and found it.

**Comment by ydamigos** [comment]
I created a WIP PR for zephyr here #5163.

**Comment by ydamigos** [comment]
If commit 94dd362 fixes a stm32 usb bug for stm32f4 family, you should create a PR in Zephyr for it.

**Comment by qianfan-Zhao** [comment]
I think the branch is stable at least on my stm32f1 board. please review my code

**Comment by ydamigos** [comment]
Which board do you use? Which SoC does you board have?
I don't think commit cb6cd04 is needed. PMA could be configured after HAL_PCD_Start.
I will test if commit e70e7ab makes any difference on my boards. 
Please rebase your PR against the latest stm32-usb-v2 branch.

**Comment by qianfan-Zhao** [comment]
my board is custom STM32F103RC board. it doesn't has pull-up resistor enable pin. USB DP was pull-up by 1k5 resistor in hardware. 

are you sure PMA can be configured after HAL_PCD_Start?  i don't think so, i will read the code generated by cubemx to find more details.

please make sure e70e7ab can work fine on your board.

**Comment by ydamigos** [comment]
> are you sure PMA can be configured after HAL_PCD_Start? i don't think so, i will read the code generated by cubemx to find more details.

I have checked the memory area using openocd debugger and it is configured fine.

**Comment by qianfan-Zhao** [comment]
> I have checked the memory area using openocd debugger and it is configured fine.

are you test this based on e452f37 ?

**Comment by ydamigos** [comment]
>   >  I have checked the memory area using openocd debugger and it is configured fine.
> 
> are you test this based on e452f37 ?

No, I have tested it using my latest stm32-usb-v2 branch. We need to dynamically configure PMA. If we configure PMA in init function we restrict the driver.

**Comment by qianfan-Zhao** [comment]
I reread the code generated by cubemx：

1. Yes, we can dynamically config PMA after HAL_PCD_Start. 
HAL_PCDEx_PMAConfig save address to a variable 'pmaadress', write this variable to hardware register  when HAL_PCD_EP_Open . 
so i will remove e452f376a and cb6cd040ef

2. we **should** remove usb_dc_ep_clear_stall in usb_dc_ep_enable
please see the hal lib for stm32f1, usb device only series
usb_dc_ep_enable first call HAL_PCD_EP_Open, that will set endpoint's status to USB_EP_TX_NAK

```
if (ep->doublebuffer == 0) 
  {
    if (ep->is_in)
    {
      /*Set the endpoint Transmit buffer address */
      PCD_SET_EP_TX_ADDRESS(USBx, ep->num, ep->pmaadress);
      PCD_CLEAR_TX_DTOG(USBx, ep->num);
      /* Configure NAK status for the Endpoint*/
      PCD_SET_EP_TX_STATUS(USBx, ep->num, USB_EP_TX_NAK); 
    }
```

But  usb_dc_ep_clear_stall do this:
```
HAL_StatusTypeDef USB_EPClearStall(USB_TypeDef *USBx, USB_EPTypeDef *ep)
{
  if (ep->is_in)
  {
    PCD_CLEAR_TX_DTOG(USBx, ep->num);
    PCD_SET_EP_TX_STATUS(USBx, ep->num, USB_EP_TX_VALID);
  }
  else
  {
    PCD_CLEAR_RX_DTOG(USBx, ep->num);
    PCD_SET_EP_RX_STATUS(USBx, ep->num, USB_EP_RX_VALID);
  }
  return HAL_OK;
}
```

SO if the endpoint is an IN-endpoint, clear stall will change it's status from USB_EP_TX_NAK to USB_EP_TX_VALID.  I had test cdc-acm example if not remove clear stall after enable endpoint, next is the usb packet captured by usb hardware monitor:
clear_stall

3. I will close this pr, create new only container e70e7abd00, do you agree?

**Comment by ydamigos** [comment]
> we should remove usb_dc_ep_clear_stall in usb_dc_ep_enable

I didn't have time to check it but I will do it in the next days.

> I will close this pr, create new only container e70e7ab, do you agree?

Please close this PR. Don't create a new one, if everything works fine with this change, I will take care of it in my PR and add you there. 
Is this "Signed-off-by: Qianfan Zhao <qianfanguijin@163.com>" correct? Why do you use different github accounts? It is better to stick with one and fix your "Signed-off-by:" signature (you are using different here and different to Zephyr)?

**Comment by qianfan-Zhao** [comment]
gmail is not avaliable in my country, so i using 163 email, not gmail.

**Comment by ydamigos** [comment]
I was talking about different github accounts.

**Pull request closed without merging**
